version: 0.1

phases:
  build:
    commands:
      - echo Converter build started on `date`
      - echo Compiling the Python code...
      - echo Running Tests...
      - python converterTests.py
  post_build:
    commands:
      - echo Hey, Build completed on `date` woo hoo!
artifacts:
  files:
    - application.py
    - Converter.py
    - converterTests.py
    - requirements.txt
    - templates/index.html
    - templates/layout.html
    - templates/temp_converter.html
